### ISSUE TITLE
Customize output printlns

### ISSUE THREAD

**Issue by weavejester** [pmonks/tools-pom#8]
Would it be possible to add options in to customize the output `println`s? Or just an option to exclude the emojis? They're causing me a few issues, and my solution of using `with-redefs` to redefine `println` with an emoji filter is not particularly elegant 😅.

**Comment by pmonks** [comment]
Yes absolutely - I'll just get rid of them.  They're a hangover from my "mucking about" phase of development.  😉

**Comment by pmonks** [comment]
Ok this should be fixed in v1.0.31 - please lmk if you're still having issues!
